package rules

import com.sbnz.workoutrecommender.facts.RegisteredUserInfo;
import com.sbnz.workoutrecommender.facts.WorkoutInfo;
import com.sbnz.workoutrecommender.model.PreviousExperienceLevel;
import com.sbnz.workoutrecommender.model.ExerciseDifficultyLevel;
import com.sbnz.workoutrecommender.model.Rating;

rule "User previous experience beginner"
    when
    	$regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.BEGINNER)
    	$workInfo: WorkoutInfo()
    then
        modify($workInfo) {
            setExerciseDifficultyLevel(ExerciseDifficultyLevel.BEGINNER),
            setNumberOfBeginner($workInfo.getNumberOfExercises()),
            setNumberOfIntermediate(0),
            setNumberOfAdvanced(0)
        }
end

rule "User previous experience intermediate"
    when
    	$regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.INTERMEDIATE)
    	$workInfo: WorkoutInfo()
    then
        modify($workInfo) {
            setExerciseDifficultyLevel(ExerciseDifficultyLevel.INTERMEDIATE),
            setNumberOfIntermediate($workInfo.getNumberOfExercises()),
            setNumberOfBeginner(0),
            setNumberOfAdvanced(0)
        }
end

rule "User previous experience advanced"
    when
    	$regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.ADVANCED)
    	$workInfo: WorkoutInfo()
    then
        modify($workInfo) {
            setExerciseDifficultyLevel(ExerciseDifficultyLevel.ADVANCED),
            setNumberOfAdvanced($workInfo.getNumberOfExercises()),
            setNumberOfBeginner(0),
            setNumberOfIntermediate(0)
        }
end

rule "User previous experience BEGINNER, rating VERY_EASY"
    when
        $regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.BEGINNER)
        $workInfo: WorkoutInfo(rating == Rating.VERY_EASY)
    then
        modify($workInfo) {
            setNumberOfBeginner($workInfo.getNumberOfBeginner() - 1),
            setNumberOfAdvanced($workInfo.getNumberOfAdvanced() + 1)
        }
end

rule "User previous experience BEGINNER, rating EASY"
    when
        $regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.BEGINNER)
        $workInfo: WorkoutInfo(rating == Rating.EASY)
    then
        modify($workInfo) {
            setNumberOfBeginner($workInfo.getNumberOfBeginner() - 1),
            setNumberOfIntermediate($workInfo.getNumberOfIntermediate() + 1)
        }
end

rule "User previous experience BEGINNER, rating VERY_HARD"
    when
        $regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.BEGINNER)
        $workInfo: WorkoutInfo(rating == Rating.VERY_HARD)
    then
        modify($workInfo) {
            setNumberOfExercises($workInfo.getNumberOfExercises() - 1),
            setNumberOfIntermediate(0),
            setNumberOfAdvanced(0),
            setNumberOfBeginner($workInfo.getNumberOfExercises())
        }
end

rule "User previous experience INTERMEDIATE, rating VERY_EASY"
    when
        $regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.INTERMEDIATE)
        $workInfo: WorkoutInfo(rating == Rating.VERY_EASY)
    then
        modify($workInfo) {
            setNumberOfExercises($workInfo.getNumberOfExercises() + 1),
            setNumberOfAdvanced($workInfo.getNumberOfAdvanced() + 2),
            setNumberOfIntermediate($workInfo.getNumberOfIntermediate() - 1)
        }
end

rule "User previous experience INTERMEDIATE, rating EASY"
    when
        $regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.INTERMEDIATE)
        $workInfo: WorkoutInfo(rating == Rating.EASY)
    then
        modify($workInfo) {
            setNumberOfIntermediate($workInfo.getNumberOfIntermediate() - 1),
            setNumberOfAdvanced($workInfo.getNumberOfAdvanced() + 1)
        }
end

rule "User previous experience INTERMEDIATE, rating VERY_HARD"
    when
        $regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.INTERMEDIATE)
        $workInfo: WorkoutInfo(rating == Rating.VERY_HARD)
    then
        modify($workInfo) {
            setNumberOfExercises($workInfo.getNumberOfExercises() - 1)
        }
end

rule "User previous experience ADVANCED, rating VERY_EASY"
    when
        $regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.ADVANCED)
        $workInfo: WorkoutInfo(rating == Rating.VERY_EASY)
    then
        modify($workInfo) {
            setNumberOfExercises($workInfo.getNumberOfExercises() + 2),
            setNumberOfAdvanced($workInfo.getNumberOfExercises())
        }
end

rule "User previous experience ADVANCED, rating EASY"
    when
        $regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.ADVANCED)
        $workInfo: WorkoutInfo(rating == Rating.EASY)
    then
        modify($workInfo) {
            setNumberOfExercises($workInfo.getNumberOfExercises() + 1),
            setNumberOfAdvanced($workInfo.getNumberOfExercises())
        }
end

rule "User previous experience ADVANCED, rating HARD"
    when
        $regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.ADVANCED)
        $workInfo: WorkoutInfo(rating == Rating.HARD)
    then
        modify($workInfo) {
            setNumberOfExercises($workInfo.getNumberOfExercises() - 1),
            setNumberOfAdvanced($workInfo.getNumberOfExercises())
        }
end

rule "User previous experience ADVANCED, rating VERY_HARD"
    when
        $regUser: RegisteredUserInfo(previousExperienceLevel == PreviousExperienceLevel.ADVANCED)
        $workInfo: WorkoutInfo(rating == Rating.VERY_HARD)
    then
        modify($workInfo) {
            setNumberOfExercises($workInfo.getNumberOfExercises() - 2),
            setNumberOfAdvanced($workInfo.getNumberOfExercises())
        }
end
