package rules

import com.sbnz.workoutrecommender.facts.RegisteredUserInfo;
import com.sbnz.workoutrecommender.model.PreviousExperienceLevel;

rule "Months of training is below 12"
    when
    	$regUser: RegisteredUserInfo(monthsOfPrevTraining < 12)
    then
        System.out.println("Months of training below 12, set exp lvl to BEGINNER");
        modify($regUser) {
            setPreviousExperienceLevel(PreviousExperienceLevel.BEGINNER)
        }
end

rule "Months of training is between 12 and 36"
    when
    	$regUser: RegisteredUserInfo((monthsOfPrevTraining >= 12) && (monthsOfPrevTraining < 36))
    then
        System.out.println("Months of training between 12 and 36, set exp lvl to INTERMEDIATE");
        modify($regUser) {
            setPreviousExperienceLevel(PreviousExperienceLevel.INTERMEDIATE)
        }
end

rule "Months of trainig is above 36"
    when
    	$regUser: RegisteredUserInfo(monthsOfPrevTraining >= 36)
    then
        System.out.println("Months of training above 36, set exp lvl to ADVANCED");
        modify($regUser) {
            setPreviousExperienceLevel(PreviousExperienceLevel.ADVANCED)
        }
end